name: ClearMapDoc
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9  # constraining seems to speed up resolution
  - pip
  - ipython
#
  - docutils
  - sphinx
  - sphinx-copybutton
  - sphinx-design
  - nbsphinx
  - pydata-sphinx-theme
#
  - vispy
  - pyopengl
  - pyqt<6
  - pyqtwebengine
  - pyqtgraph=0.12  # Problem with pyqtgraph import of QWidgets with 0.13
  - opencv
  - cython<3  # get_distutils_extension has been removed from pyximport in >=3
  - numpy
  - scipy
  - pandas<2  # Groupby syntax changes
  - pyarrow
  - matplotlib
  - scikit-image
  - scikit-learn
  - graph-tool<=2.45  # Cannot remove self loops with later versions
  - python-igraph
  - pytorch<=1.11  # could probably upgrade
  - cudatoolkit=11.6
  - configobj
  - natsort
  - tifffile<2020.9.22  # Adds "Use DimensionOrder to determine axes order in OmeXml." which breaks ClearMap.IO
  - xmltodict  # to compensate for old tifffile
  - pygments
  - qdarkstyle
  - qtpy  # for qdarkstyle
  - psutil  # required for python < 3.9 for cancelable ProcessPoolExecutors
  - tqdm
  - mpld3  # WARNING Maybe pip
  - lxml
  - pyamg
  - quantities
  - pip:
    - sphinxcontrib.youtube
    - sphinx-autopackagesummary
    - sphinx-carousel
variables:
  PYTHONNOUSERSITE: 1
